### ISSUE TITLE
ModuleNotFoundError raised if pytube is not installed beforehand

### ISSUE THREAD

**Issue by approachcircle** [jamieabw/Youtube_Downloader_GUI#2]
# issue
if pytube is not manually installed via pip, a ModuleNotFoundError is raised.
# solution
either use `os.system("pip install pytube")` which assumes that pip is in the user's PATH (not recommended) or add a 'prerequisites' section in the README.md prompting users to install pytube using pip before running.

**Comment by jamieabw** [comment]
fixed using try when importing pytube - now prompts users to install
